name: env-his
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4==4.12.0
  - numpy==1.24.2
  - pandas==1.5.3
  - pip==23.0.1
  - pre-commit==2.21.0
  - python==3.10.10
  - requests==2.28.1
  - scipy==1.10.1
  - selenium==4.7.2
  - setuptools==65.6.3
  - tqdm==4.65.0
  - pip:
    - black==23.1.0
    - coverage==7.2.2
    - Django==4.1.7
    - djangorestframework==3.14.0
    - fake-useragent==1.1.1
    - pyproj==3.5.0
