# Generated by Django 4.1.7 on 2023-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publictransit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="isin_boundary",
            field=models.BooleanField(default=True),
        ),
    ]
