name: Django tests with Conda

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: env-his-dev.yaml

    - name: Activate Conda environment
      run: conda activate base

    - name: Install dependencies
      run: conda env update --file env-his-dev.yaml

    - name: Run tests
      run: |
        python manage.py test
